CREATE USER sales_etl
IDENTIFIED BY sales123;

GRANT CREATE SESSION TO sales_etl;
GRANT CREATE TABLE TO sales_etl;
GRANT CREATE VIEW TO sales_etl;
GRANT CREATE SEQUENCE TO sales_etl;
GRANT UNLIMITED TABLESPACE TO sales_etl;