CREATE TABLE SUPPLIER
(
    SUPPLIER_ID NUMBER,
    SUPPLIER_NAME VARCHAR2(200)
);

CREATE TABLE ITEM
(
    ITEM_CODE VARCHAR2(20),
    ITEM_DESCRIPTION VARCHAR2(300),
    ITEM_TYPE VARCHAR2(50)
);

CREATE TABLE SALES
(
    YEAR NUMBER,
    MONTH NUMBER,
    ITEM_CODE VARCHAR2(20),
    SUPPLIER_ID NUMBER,
    RETAIL_SALES NUMBER(12,2),
    RETAIL_TRANSFERS NUMBER(12,2),
    WAREHOUSE_SALES NUMBER(12,2)
);