ALTER TABLE SUPPLIER
ADD CONSTRAINT PK_SUPPLIER
PRIMARY KEY (SUPPLIER_ID);

ALTER TABLE ITEM
ADD CONSTRAINT PK_ITEM
PRIMARY KEY (ITEM_CODE);

ALTER TABLE SALES
ADD CONSTRAINT FK_SALES_SUPPLIER
FOREIGN KEY (SUPPLIER_ID)
REFERENCES SUPPLIER (SUPPLIER_ID);

ALTER TABLE SALES
ADD CONSTRAINT FK_SALES_ITEM
FOREIGN KEY (ITEM_CODE)
REFERENCES ITEM (ITEM_CODE);

ALTER TABLE SUPPLIER
MODIFY SUPPLIER_ID NOT NULL;

ALTER TABLE ITEM
MODIFY ITEM_CODE NOT NULL;

ALTER TABLE SALES
MODIFY YEAR NOT NULL;

ALTER TABLE SALES
MODIFY MONTH NOT NULL;

ALTER TABLE SALES
MODIFY ITEM_CODE NOT NULL;

ALTER TABLE SALES
MODIFY SUPPLIER_ID NOT NULL;